spring:
  application:
    name: dubbo-provider-test
server:
  port: 9092
dubbo:
  application:
    name: dubbo-provider-test
  registry:
    protocol: zookeeper
    address: localhost:2181
  protocol:     #协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受。
    name: dubbo
    port: 20880
  scan:
    basePackages: com.demo.dubbo.test.service